### ISSUE TITLE
插件启动时加载失败

### ISSUE THREAD

**Issue by ztsinsun** [lgc-NB2Dev/nonebot-plugin-multincm#18]
12-15 09:13:20 [ERROR] nonebot | Failed to import &quot;nonebot_plugin_multincm&quot;
Traceback (most recent call last):
  File &quot;&lt;string&gt;&quot;, line 14, in &lt;module&gt;
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py&quot;, line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py&quot;, line 64, in load_all_plugins
    return manager.load_all_plugins()
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 176, in load_all_plugins
    return set(
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 177, in &lt;genexpr&gt;
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
&gt; File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 142, in load_plugin
    module = importlib.import_module(name)
  File &quot;/usr/lib/python3.10/importlib/__init__.py&quot;, line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1006, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 688, in _load_unlocked
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py&quot;, line 242, in exec_module
    super().exec_module(module)
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 883, in exec_module
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 241, in _call_with_frames_removed
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot_plugin_multincm/__init__.py&quot;, line 5, in &lt;module&gt;
    from . import __main__ as __main__  # noqa: E402
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot_plugin_multincm/__main__.py&quot;, line 38, in &lt;module&gt;
    from .config import config
  File &quot;/nonebot/nepra/.venv/lib/python3.10/site-packages/nonebot_plugin_multincm/config.py&quot;, line 38, in &lt;module&gt;
    config: ConfigModel = ConfigModel.parse_obj(get_driver().config.dict())
  File &quot;pydantic/main.py&quot;, line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File &quot;pydantic/main.py&quot;, line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for ConfigModel
ncm_phone
  str type expected (type=type_error.str)
ncm_password
  str type expected (type=type_error.str)

**Comment by lgc2333** [comment]
配置问题
