### ISSUE TITLE
非正确指令，请重新输入

### ISSUE THREAD

**Issue by Fsyxr** [lgc-NB2Dev/nonebot-plugin-multincm#2]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/85301551/a14c9d9c-ccc0-4dae-a58a-e18c9eb92cfc)
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/85301551/9980ff6c-e99b-4ae5-8f2f-f39a1ae65249)
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/85301551/d79a3b1e-50fc-413f-896b-c5175ca12bf5)
05-19 23:46:40 [SUCCESS] nonebot | OneBot V11 3012167152 | [message.group.normal]: Message 1871211449 from 344394595@[群:837289569] 'wyy TEmPTaTiON'
05-19 23:46:40 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_multincm.__main__)
05-19 23:46:41 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_multincm.__main__) running complete

**Comment by lgc2333** [comment]
输e退出
