### ISSUE TITLE
使用onebot v11点歌failed

### ISSUE THREAD

**Issue by Ilovexiu** [lgc-NB2Dev/nonebot-plugin-multincm#21]
```
03-23 17:46:29 [SUCCESS] nonebot | OneBot V11 2978928081 | [message.group.normal]: Message 459002439 from 2278928081@[群:571520977] '/点歌 one last kiss'
03-23 17:46:29 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=479)
03-23 17:46:32 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=479) running complete
03-23 17:46:37 [SUCCESS] nonebot | OneBot V11 2978928081 | [message.group.normal]: Message 1499096812 from 2278928081@[ 群:571520977] '1'
03-23 17:46:37 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=479)
**03-23 17:46:38 [WARNING] nonebot_plugin_multincm | Send 歌曲 card failed**
03-23 17:46:38 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=479) running complete
03-23 17:46:39 [SUCCESS] nonebot | OneBot V11 2978928081 | [notice.group_recall]: {'time': 1711187202, 'self_id': 2978928081, 'post_type': 'notice', 'notice_type': 'group_recall', 'user_id': 2978928081, 'group_id': 571520977, 'operator_id': 2978928081, 'message_id': 1769563308}
```

麻烦大佬帮忙看一下为啥会发送卡片失败呢

**Comment by XieXiLin2** [comment]
把日志等级调成 `DEBUG` 后再试一次，然后把日志发上来。

**Comment by Ilovexiu** [comment]
> 把日志等级调成 `DEBUG` 后再试一次，然后把日志发上来。

大佬怎么调日志等级呀

**Comment by XieXiLin2** [comment]
> > 把日志等级调成 `DEBUG` 后再试一次，然后把日志发上来。
> 
> 大佬怎么调日志等级呀

https://nonebot.dev/docs/appendices/config#log-level

**Comment by Ilovexiu** [comment]
> > > 把日志等级调成 `DEBUG` 后再试一次，然后把日志发上来。
> > 
> > 
> > 大佬怎么调日志等级呀
> 
> https://nonebot.dev/docs/appendices/config#log-level

[log.txt](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/files/14731055/log.txt)
这样可以吗

**Comment by lgc2333** [comment]
不用看了，llob不支持，拉格兰不知道

**Comment by lgc2333** [comment]
那就完蛋啦，都不支持，解决方法有待商榷

**Comment by Ilovexiu** [comment]
> 那就完蛋啦，都不支持，解决方法有待商榷

好的好的那我蹲一波，麻烦大佬了

**Comment by XieXiLin2** [comment]
> @lgc2333 实测"Satori"发到qq也没反应XD [LOG](https://pastebin.com/bjJaJLud)

本插件暂只支持 `~onebot11` 适配器。

**Comment by XieXiLin2** [comment]
你这什么协议端连图片都发不了……

**Comment by 502milk** [comment]
http啊（捂脸

> 你这什么协议端连图片都发不了……

**Comment by XieXiLin2** [comment]
不是，我问你连 nonebot 的那边是什么端

**Comment by 502milk** [comment]
> 不是，我问你连 nonebot 的那边是什么端

就QQNT啊
https://github.com/LLOneBot/LLOneBot

**Comment by 502milk** [comment]
> 尝试更新你的 LLOnebot 或者换种协议 这边测了下，除了音乐的 json 卡片发不了和 upload_file api 没实现导致的传不了文件外，其他都没问题

json卡片要自己签名XD

**Comment by 502milk** [comment]
llonebot[3.17.0](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.17.0)版本就支持发送json了，但是要自己签名，没有给方法XD

**Comment by 502milk** [comment]
https://xiaoapi.cn/?action=doc&id=61
找到一个json签名的~~能否逝一逝~~

**Comment by XieXiLin2** [comment]
> https://xiaoapi.cn/?action=doc&id=61 找到一个json签名的~能否逝一逝~

由于 API 涉及隐私内容，因此计划不变。
仍建议自行适配

**Comment by 502milk** [comment]
> > https://xiaoapi.cn/?action=doc&id=61 找到一个json签名的~能否逝一逝~
> 
> 由于 API 涉及隐私内容，因此计划不变。
> 仍建议自行适配

那能否添加配置项让我们自己填啊，自己接实在不会啊（捂脸）

**Comment by lgc2333** [comment]
不考虑接这些api，由于本插件发送`music`类型的segement，能否发出与协议端实现有关。正在尝试直接构建json卡片发送的可行性

**Comment by 502milk** [comment]
> 不考虑接这些api，由于本插件发送`music`类型的segment，能否发出与协议端实现有关。正在尝试直接构建json卡片发送的可行性

那有适配Satori的计划吗

**Comment by lgc2333** [comment]
有适配多平台的想法

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/releases/tag/v0.5.0.dev10
