### ISSUE TITLE
点歌failed,显示base64文件下载失败

### ISSUE THREAD

**Issue by danel-phang** [lgc-NB2Dev/nonebot-plugin-multincm#22]
[日志文本文档.txt](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/files/14820040/default.txt)
<img width="842" alt="屏幕截图 2024-04-01 142036" src="https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/145145476/c24f28f3-c81a-497d-8575-153ec8852f74">

**Comment by danel-phang** [comment]
麻烦大佬们帮忙看看是什么情况

**Comment by lgc2333** [comment]
更改LLQQNT的安装位置

**Comment by danel-phang** [comment]
> 更改LLQQNT的安装位置
NICE!! 问题解决了
