### ISSUE TITLE
使用发送语音功能无响应

### ISSUE THREAD

**Issue by axlmly** [lgc-NB2Dev/nonebot-plugin-multincm#24]
llob的日志里看到 收到反向Websocket消息 {"action":"get_group_list","params":{},"echo":41792} 好像只获取了列表
05-07 05:19:39 [SUCCESS] nonebot | OneBot V11 2922674617 | [message.group.normal]: Message -2147406096 from 1206147964@[群:623987016] '！语音'
05-07 05:19:39 [DEBUG] nonebot | Checking for matchers in priority 0...
05-07 05:19:39 [DEBUG] nonebot | Checking for matchers in priority 1...
05-07 05:19:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=544)
05-07 05:19:39 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=544)
05-07 05:19:39 [DEBUG] nonebot | Running handler Dependent(call=_)
05-07 05:19:40 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_multincm.__main__, lineno=544) running complete
05-07 05:19:40 [DEBUG] nonebot | Checking for matchers completed
nb的也是

**Comment by FalfaChino** [comment]
- `NCM_ENABLE_RECORD` is `True`?
- 如果还是不行就是发不出去（要么协议端不支持要么看协议端报错）
