### ISSUE TITLE
Event message.private.friend is ignored

### ISSUE THREAD

**Issue by Echoflare** [lgc-NB2Dev/nonebot-plugin-multincm#29]
点歌后发送数字无响应
![Image_1720521030605](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/144500846/af51d8c2-dcc8-4c2e-9548-44ac033954be)
![Image_1720520469558](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/144500846/7151e864-dd46-452f-8b45-31c0d6bbaff5)

**Comment by lgc2333** [comment]
未复现，排查是否为其他插件的问题

**Comment by Echoflare** [comment]
经排查发现是nonebot自带的single_session插件引起的问题
