### ISSUE TITLE
启动报错 There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [lgc-NB2Dev/nonebot-plugin-multincm#3]
File "G:\conda_env\nb\lib\site-packages\nonebot_plugin_multincm\__init__.py", line 5, in <module>
    from . import __main__ as __main__  # noqa: E402
  File "G:\conda_env\nb\lib\site-packages\nonebot_plugin_multincm\__main__.py", line 33, in <module>
    from .data_source import (
  File "G:\conda_env\nb\lib\site-packages\nonebot_plugin_multincm\data_source.py", line 183, in <module>
    asyncio.get_event_loop().run_until_complete(login())
  File "G:\conda_env\nb\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by lgc2333** [comment]
有没有插件在启动时使用了`asyncio.run()`

**Comment by Misaka-Mikoto-Tech** [comment]
是的，就是这个问题，如果此插件不是第一个被加载，那么大概率会报错，建议改成 asyncio.run()

**Comment by lgc2333** [comment]
这个问题困扰我好久了，因为其他大部分插件都没用 `asyncio.run()`，我用了就有概率得报错

**Comment by Misaka-Mikoto-Tech** [comment]
这感觉是`python`的一个设计失误，主线程第一个使用 `get_event_loop()`的不会报错，因为 `python` 会自动帮你创建一个`loop`，但是一旦有人调用了`asyncio.run`, 再次调用就不会帮你创建了，此时就会报错，解决办法就是如果在非` loop` 中调用的函数（一般是没有 `async` 的函数），如果想要执行 `async` 函数，那么就用 `asyncio.run()`，而在插件初始化时，被调用的代码就是不在 `loop` 中执行的，因此此时需要用 `asyncio.run()` 更保险

**Comment by Misaka-Mikoto-Tech** [comment]
> 这个问题困扰我好久了，因为其他大部分插件都没用 `asyncio.run()`，我用了就有概率得报错

这个函数不能在`loop`中调用，插件初始化时使用是没问题的, `nonebot.load_plugin()` 函数不是在`loop` 中执行的
