### ISSUE TITLE
歌名点歌模式无法返回歌曲信息

### ISSUE THREAD

**Issue by enKl03B** [lgc-NB2Dev/nonebot-plugin-multincm#30]
如图，我发送了歌曲搜索请求，但在输入 id 后没有反应，后台报：
[INFO] nonebot | Event message.group.normal is ignored
![f30de22a5ed6dd859323b857f2c63bf2](https://github.com/user-attachments/assets/b4ef2e48-1206-4434-9f20-7a1137becfb7)
请问是什么原因，谢谢

**Comment by lgc2333** [comment]
可能是nb内置插件single_session造成的，禁用即可
