### ISSUE TITLE
点歌发生错误，无法点歌

### ISSUE THREAD

**Issue by NAOLIU** [lgc-NB2Dev/nonebot-plugin-multincm#31]
使用的是Nonebot2 + LLOneBot
![网易云点歌报错](https://github.com/user-attachments/assets/4acf57f3-b957-484f-b59b-9ea9e57bfc13)
点歌后出现菜单，随后输入数字，便出现报错
网易云账号已经显示成功登录

**Comment by lgc2333** [comment]
登录有会员的账号后再次尝试
