### ISSUE TITLE
发送音乐卡片失败card failed

### ISSUE THREAD

**Issue by apk5418** [lgc-NB2Dev/nonebot-plugin-multincm#32]
napcat2.5.0版本
在napcat的onebot11.json设置了音乐签名地址
别的插件可以发音乐卡片
![QQ图片20240915184141](https://github.com/user-attachments/assets/b28fe241-bd71-45a4-bf08-ef972792c50f)
![QQ图片20240915184148](https://github.com/user-attachments/assets/2ab31c36-b17b-475c-a8f1-e7c094362fea)
![QQ图片20240915184153](https://github.com/user-attachments/assets/eaf9b3ca-5471-4f8a-8245-a68a6fc14d08)

**Comment by XieXiLin2** [comment]
NapCat 侧有没有提示什么错误信息

**Comment by apk5418** [comment]
> NapCat 侧边有没有提示什么错误信息

![QQ图片20240915185014](https://github.com/user-attachments/assets/63325f64-9890-4357-afdd-b2a9b71257a3)

**Comment by apk5418** [comment]
这边napcat更新了2.5.1，napcat就没有报错了但还是Send Song card failed

**Comment by lgc2333** [comment]
`LOG_LEVEL` 换成 `DEBUG` 看下报错信息

**Comment by apk5418** [comment]
> `LOG_LEVEL`换成`DEBUG`看报告错误信息

[2024-09-20.log](https://github.com/user-attachments/files/17073756/2024-09-20.log)
这个可以吗？我用了另一个插件对比

**Comment by apk5418** [comment]
> 尝试https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/releases/tag/v1.1.2

ok可以了，大佬nb😋😋😋
