### ISSUE TITLE
成功登录网易云账号后音乐卡片仍然是QQ音乐

### ISSUE THREAD

**Issue by Tigrex-Dai** [lgc-NB2Dev/nonebot-plugin-multincm#33]
使用的是Nonebot2 + LLOneBot

**Comment by XieXiLin2** [comment]
正常现象，QQNT 不支持自定义 music platform type

**Comment by Tigrex-Dai** [comment]
嗯...但是不知道为什么用ncm而不是multincm时出现的卡片是网易云的？

**Comment by XieXiLin2** [comment]
https://github.com/nonebot/plugin-alconna/blob/7ac30a66081095ecd3c373eae8f0164deb025ec5/src/nonebot_plugin_alconna/builtins/uniseg/music_share.py#L150-L155

因为 alconna 在发 music_custom 的时候没有带 type_，建议去那边提 issue

**Comment by lgc2333** [comment]
> 嗯...但是不知道为什么用ncm而不是multincm时出现的卡片是网易云的？

ncm使用的不是自定义音卡

**Comment by Tigrex-Dai** [comment]
好的谢谢
