### ISSUE TITLE
匿名登录状态下点歌失败

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [lgc-NB2Dev/nonebot-plugin-multincm#4]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/assets/1246379/a2aaac34-2a0b-4d50-9ce0-4de96e8e5f7f)
发送指令 `点歌 可能` 报错，debug发现是`SongSearchResult.songs[1].privilege.plLevel` 字段返回了 `none` 字符串

**Comment by lgc2333** [comment]
nmb竟然是个字符串，6
